# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-24 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=200)),
                ('pubDate', models.DateField()),
            ],
        ),
    ]
